### ISSUE TITLE
Which JDK version should I use and where to get it? 

### ISSUE THREAD

**Issue by alberttwong** [RedHatWorkshops/rider-auto-openshift#12]

**Comment by alberttwong** [comment]
`yum install java-1.7.0-openjdk-devel` ????

**Comment by christian-posta** [comment]
Use JDK 1.8 https://github.com/RedHatWorkshops/rider-auto-openshift/blob/master/pom.xml#L84

**Comment by alberttwong** [comment]
done..  I also tried it and still failed.
